frameworkVersion: '3'

service: safety-api

provider:
  name: aws
  apiName: safety-api-gateway
  runtime: java11
  region: eu-central-1
  environment:
    JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

package:
  artifact: target/safetyapi-0.0.1-SNAPSHOT.jar

functions:
  api:
    name: safety-api-lambda
    handler: com.github.danrog303.safetyapi.ApplicationAwsLambdaEntrypoint::handleRequest
    timeout: 30
    snapStart: true
    memorySize: 2048
    events:
      - http:
          path: /{proxy+}
          method: any